### ISSUE TITLE
Move to karaxnim?

### ISSUE THREAD

**Issue by planetis-m** [nim-lang-cn/html2karax#3]
I think it would make sense to have this tool under the https://github.com/karaxnim organization. Any objections?

**Comment by ringabout** [comment]
@planetis-m , though I'm not the owner of this repo(I can't make a decision), I agree with you. 

What's your opinion? @gogolxdong

**Comment by lbcheng888** [comment]
yes, good idea!

**Comment by ringabout** [comment]
@planetis-m

See discuss at
https://discord.com/channels/371759389889003530/764946138109050893/854425795836379176
